### ISSUE TITLE
A newer version of Backbone.js is available (1.0.0)

### ISSUE THREAD

**Issue by micapam** [codebrew/backbone-rails#153]
The version of Backbone.js has various bugs e.g. underscore finders aren't fully supported (see https://github.com/documentcloud/backbone/issues/2228). 

Are there plans to upgrade the version of Backbone.js to its current version, 1.1.0?

**Comment by sporkmonger** [comment]
So... It's great and all that master is up-to-date, but it's kinda been a *really* long time and the official release is still tracking an ancient version of Backbone, which just seems kinda weird for a project that appears to be reasonably active?

**Comment by manusajith** [comment]
@sporkmonger I don't have push access to Rubygems yet. Will be releasing a new version as soon as I get that.

**Comment by sporkmonger** [comment]
Ah, I see. Did the gem change hands?
