### ISSUE TITLE
Generators does not work with RoR4

### ISSUE THREAD

**Issue by mspanc** [codebrew/backbone-rails#169]
Generators are not available in RoR4

**Comment by UncleWaldo** [comment]
Running in to the same issue today

using:

    Using rails 4.2.1
    Using rails-backbone 1.1.2 from git://github.com/codebrew/backbone-rails.git (at master)

What makes me wondering `$ rails g backbone:install`

      insert  app/assets/javascripts/application.js
       exist  app/assets/javascripts/backbone/routers
    identical  app/assets/javascripts/backbone/routers/.gitkeep
       exist  app/assets/javascripts/backbone/models
    identical  app/assets/javascripts/backbone/models/.gitkeep
       exist  app/assets/javascripts/backbone/views
    identical  app/assets/javascripts/backbone/views/.gitkeep
       exist  app/assets/javascripts/backbone/templates
    identical  app/assets/javascripts/backbone/templates/.gitkeep
    identical  app/assets/javascripts/backbone/projectrail.js.coffee

but then: `$ rails g backbone model:log description:string`
     
    Could not find generator 'backbone'. Maybe you meant 'task' or 'resource' or 'scaffold'

So interestingly the generator is known during the installation, but that's it. As you see, the `backbone:install` ran twice without any problem. Maybe someone found the reason, or even a solution to this. thanks.

**Comment by recurser** [comment]
I had the same issue and `spring stop` resolved it.
