### ISSUE TITLE
Default coffeescript dependency is kinda wrong

### ISSUE THREAD

**Issue by je-allard** [codebrew/backbone-rails#182]
By default, a new rails project already comes with ```coffee-rails``` which already depends on ```coffee-script```.
Why not make backbone-rails depending on ```coffee-rails```instead ?

This would fix this kind of problem
![selection_038](https://cloud.githubusercontent.com/assets/943725/5403206/fe7d76f2-8158-11e4-9c49-65095592750c.png)

**Comment by backus** [comment]
+1

**Comment by manusajith** [comment]
@je-allard I guess we can close this as #183 is merged
